version: 0.0
os: linux
files:
  - source: /wordpress
    destination: /var/www/ekansh-test.squareops.xyz/html/
hooks:
  ApplicationStop:
     - location: scripts/stop_server.sh
       timeout: 300
       runas: ubuntu
  ApplicationStart:
     - location: scripts/start_server.sh
       timeout: 300
       runas: ubuntu
  AfterInstall:
     - location: scripts/after_installation.sh
       timeout: 300
       runas: ubuntu
