version: 0.2
env:
  parameter-store:
    DB_Name: database_name_here
    UserName: username_here
    Password: password_here
    Host: localhost
phases:
    build:
       commands:
         - sed -i 's/database_name_here/'$DB_Name'/' wp-config 
         - sed -i 's/username_here/'$UserName'/' wp-config
         - sed -i 's/password_here/'$Password'/' wp-config
         - sed -i 's/localhost/'$Host'/' wp-config